### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Hashable'

### ISSUE THREAD

**Issue by D3VinEd** [xTEddie/Scrapstagram#3]
Hey, following Error on fresh venv.

```
\Scrapstagram\venv\Scripts\python.exe \Scrapstagram\scrapstagram.py bitcoin 
Traceback (most recent call last):
  File "\Scrapstagram\scrapstagram.py", line 163, in <module>
    with Scrapstagram() as scrapper:
  File "\Scrapstagram\scrapstagram.py", line 28, in __init__
    self.settings = yaml.load(file)
  File "\Scrapstagram\venv\lib\site-packages\yaml\__init__.py", line 72, in load
    return loader.get_single_data()
  File "\Scrapstagram\venv\lib\site-packages\yaml\constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "\Scrapstagram\venv\lib\site-packages\yaml\constructor.py", line 46, in construct_document
    for dummy in generator:
  File "\Scrapstagram\venv\lib\site-packages\yaml\constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "\Scrapstagram\venv\lib\site-packages\yaml\constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "\Scrapstagram\venv\lib\site-packages\yaml\constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'

Process finished with exit code 1
```

**Comment by warrior8008** [comment]
Same here
